Repository ipfs/ipfs-desktop, pull requests merged in 2020-04, with the labels that each got.

#1403 chore: update dependencies
  package-lock.json
  package.json
Labels: dependencies, kind/maintenance

#1404 chore: update to electron 8.x
  package-lock.json
  package.json
Labels: dependencies, kind/maintenance

#1406 refactor: remove babel
  .babelrc
  .gitignore
  electron-builder.yml
  package-lock.json
  package.json
  src/add-to-ipfs.js
  src/analytics.js
  src/app-menu.js
  src/argv-files-handler.js
  src/auto-launch.js
  src/auto-updater/index.js
  src/auto-updater/quit-and-install.js
  src/common/consts.js
  src/common/logger.js
  src/common/notify.js
  src/common/store.js
  src/create-toggler.js
  src/daemon/config.js
  src/daemon/daemon.js
  src/daemon/index.js
  src/dialogs/dialog.js
  src/dialogs/errors.js
  src/dialogs/index.js
  src/dialogs/ipfs-not-running.js
  src/dialogs/select-directory.js
  src/dock.js
  src/download-hash.js
  src/exec-or-sudo.js
  src/i18n.js
  src/index.js
  src/ipfs-on-path/index.js
  src/ipfs-on-path/scripts/backup.js
  src/ipfs-on-path/scripts/consts.js
  src/ipfs-on-path/scripts/install.js
  src/ipfs-on-path/scripts/uninstall.js
  src/move-repository-location.js
  src/npm-on-ipfs/index.js
  src/npm-on-ipfs/package.js
  src/protocol-handlers.js
  src/second-instance.js
  src/setup-global-shortcut.js
  src/take-screenshot.js
  src/tray.js
  src/webui/connection-status.js
  src/webui/index.js
  src/webui/open-external.js
  src/webui/preload.js
  src/webui/screenshot.js
  test/e2e/launch.e2e.js
  test/e2e/utils/include.js
  test/e2e/utils/ipfsd.js
  test/unit/create-toggler.spec.js
  test/unit/dock.spec.js
  test/unit/mocks/electron.js
  test/unit/mocks/logger.js
  test/unit/mocks/store.js
  test/unit/mocks/webui.js
Labels: kind/architecture, kind/maintenance

#1405 fix: write path when it does not exist
  src/daemon/index.js
Labels: P1, kind/bug

#1407 feat: run garbage collector
  assets/locales/en.json
  src/run-gc.js
  src/tray.js
Labels: kind/enhancement

#1437 fix(BREAKING): ipfs daemon flags
  src/common/store.js
Labels: P0, kind/bug

#1438 fix: repo fsck is deprecated
  src/daemon/config.js
  src/daemon/daemon.js
Labels: P0, kind/bug

#1429 feat(ux): open Web UI at launch on Linux
  assets/locales/en.json
  src/tray.js
  src/webui/index.js
Labels: P1, area/linux

#1465 fix: ipfs on PATH on windows with spaces in binary path
  src/ipfs-on-path/scripts/bin-win/ipfs.cmd
Labels: P0, area/windows, kind/bug

#1472 fix: open directory from webui
  src/webui/preload.js
Labels: kind/bug
